### ISSUE TITLE
Downloading smplot2 unsuccessful

### ISSUE THREAD

**Issue by ChlorisF** [smin95/dataviz#1]
Hi smin95,

Thanks for creating the package. I'd like to draw rainplot using smplot2. However, I keep getting the error message when trying to download it:
> devtools::install_github('smin95/smplot2', force = TRUE)
> Downloading GitHub repo smin95/smplot2@HEAD
> Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
>   cannot open URL 'https://api.github.com/repos/smin95/smplot2/tarball/HEAD' 

Do you know possible reasons and how to fix this?

Many thanks,
Chloris

**Comment by smin95** [comment]
Hi Chloris,

Thanks for writing. I do not know the issue. If you are in China or elsewhere with firewall, then you might need to turn on your VPN to enable your RStudio to access github before you run the code.

Best,
Sam

**Comment by ChlorisF** [comment]
Hi Sam,

Thank you a lot for the prompt reply. I'm indeed in China right now, with VPN working properly (or at least I think so). The weird thing is that I can open the link directly and download the zip file, but unable to access it via RStudio... I tried to manually copy-paste the file and unzip it in the R directory and it seems to work:

> * installing *source* package 'smplot2' ...
> ** using staged installation
> ** R
> ** byte-compile and prepare package for lazy loading
> ** help
> *** installing help indices
>   converting help for package 'smplot2'
>     finding HTML links ... done
>     sm_auc                                  html  
>     sm_auc_all                              html  
>     sm_auc_list                             html  
>     sm_bar                                  html  
> ...
>     sm_violin                               html  
> ** building package indices
> ** testing if installed package can be loaded from temporary location
> ** testing if installed package can be loaded from final location
> ** testing if installed package keeps a record of temporary installation path
> * DONE (smplot2)

However, when adding sm_raincloud() to a ggplot, I get the below error message:

> Error in geom_half_boxplot(position = <environment>, side = "r", errorbar.draw = FALSE,  : 
>   could not find function "geom_half_boxplot"
> Called from: do.call("geom_half_boxplot", modifyList(list(position = position_nudge(x = position_nudge_vector[2]), 
>     side = which_side, errorbar.draw = FALSE, width = 0.2, color = "black"), 
>     boxplot.params))

Do you have any idea what went wrong?

Thanks,
Chloris

**Comment by smin95** [comment]
Hi Chloris,

What you are doing right now is manually downloading everything to run smplot2 smoothly. Unfortunately, smplot2 depends on several external packages, and you are missing them (one of which is 'gghalves'). Using the standard way to download smplot2 allows you to download smplot2 and all its dependencies at once.

Instead I suggest:
1. Redownload 'devtools' and see if it can download another package from Github successfully (with VPN on).
2. Check if your VPN can access Google or Youtube.

Best,
Sam

**Comment by ChlorisF** [comment]
Hi Sam,

Thanks for your support! Since the VPN worked fine for other websites, I tried to devtools to re-download another package (linkET) and it went smoothly. Then, I didn't change anything else, re-downloaded smplot2 - somehow it worked! I now have another question regarding aesthetics but maybe it'd be better to open another issue.

Best,
Chloris
